#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Feb 28, 2019 02:19:37 PM IST  platform: Windows NT

import sys
import application
import cv2
from PIL import Image, ImageTk
from threading import Thread
from nltk.tokenize import word_tokenize, sent_tokenize

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import unknown.py
    unknown.py.vp_start_gui()

def start():
    application.start()

def changelabel(text):

    w.Label4["text"]=text
    

def setImage(fname):
    image=Image.open(fname)
    photo_image=ImageTk.PhotoImage(image)
    w.Label5["image"]=photo_image
    w.Label5.image=photo_image

def setNewsImage():
    newsImage=Image.open("downloads/screenshotOfWebPage.png")
    newsImage_photo_image=ImageTk.PhotoImage(newsImage)
    w.Label6["image"]=newsImage_photo_image
    w.Label6.image=newsImage_photo_image

def setTwitterImage():
    twitterImage=Image.open("downloads/graph.png")
    twitterImage_photo_image=ImageTk.PhotoImage(twitterImage)

    w.Label7["image"]=twitterImage_photo_image
    w.Label7.image=twitterImage_photo_image

def readText():
    try:
        s=w.Entry1.get()
        #running on main thread makes the program hang 
        t1=Thread(target=application.startProcess, args=(s,))
        t1.start()
    except:
        print("Something happened, let's not talk about it")

def insertToList(summary):
    
    w.Listbox2.delete(0,tk.END)
    for sentence in summary:
        w.Listbox2.insert(tk.END,str(sentence))
        

